/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package psl.tagprocessor.parser;

public interface MyParserConstants {

  int EOF = 0;
  int S = 5;
  int SLASH = 6;
  int SLASHSLASH = 7;
  int UNION = 8;
  int PLUS = 9;
  int MINUS = 10;
  int ASSIGN = 11;
  int MATCH = 12;
  int EQ = 13;
  int NEQ = 14;
  int LT = 15;
  int LTE = 16;
  int GT = 17;
  int GTE = 18;
  int VARIABLE = 19;
  int TRUE = 20;
  int FALSE = 21;
  int INT = 22;
  int LONG = 23;
  int DOUBLE = 24;
  int STRING = 25;
  int BOOLEAN = 26;
  int SEPARATOR = 27;
  int INTEGER_LITERAL = 28;
  int DECIMAL_LITERAL = 29;
  int FLOATING_POINT_LITERAL = 30;
  int EXPONENT = 31;
  int CHARACTER_LITERAL = 32;
  int STRING_LITERAL = 33;
  int Letter = 34;
  int Digit = 35;
  int OR = 36;
  int AND = 37;
  int MOD = 38;
  int DIV = 39;
  int NCName = 40;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<S>",
    "\"/\"",
    "\"//\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"=~\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"$\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"long\"",
    "\"double\"",
    "\"String\"",
    "\"boolean\"",
    "\";\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<Letter>",
    "<Digit>",
    "\"||\"",
    "\"&&\"",
    "\"mod\"",
    "\"div\"",
    "<NCName>",
    "\"(\"",
    "\")\"",
    "\"*\"",
  };

}
